//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDream.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerUser
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int Role_Id { get; set; }
        public bool ForceChangePassword { get; set; }
        public bool IsLockedOut { get; set; }
    }
}
