//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDream.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egg
    {
        public int EggId { get; set; }
        public string Name { get; set; }
        public int EggColor { get; set; }
        public Nullable<double> WeightPer { get; set; }
    }
}
