//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDream.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeHistory
    {
        public System.Guid RecipeHistoryId { get; set; }
        public string Name { get; set; }
        public string RecipeDescription { get; set; }
        public System.DateTimeOffset CreateDate { get; set; }
        public Nullable<int> Socore { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
