//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDream.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Season
    {
        public int SeasonId { get; set; }
        public string Name { get; set; }
        public Nullable<double> Salty { get; set; }
        public Nullable<double> Sweet { get; set; }
        public Nullable<double> Spicy { get; set; }
        public Nullable<double> Bitter { get; set; }
        public Nullable<double> Sour { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
